// <auto-generated />
using LorincMarton_WebAPI.Modells;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LorincMarton_WebAPI.Migrations
{
    [DbContext(typeof(PartnerSzerzodesContext))]
    partial class PartnerSzerzodesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LorincMarton_WebAPI.Modells.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PartnerNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partnerek");
                });

            modelBuilder.Entity("LorincMarton_WebAPI.Modells.Szerzodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IgazgatoJovahagyta")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("SzerzodesSzam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SzerzodesTargya")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Szerzodesek");
                });

            modelBuilder.Entity("LorincMarton_WebAPI.Modells.Szerzodes", b =>
                {
                    b.HasOne("LorincMarton_WebAPI.Modells.Partner", "Partner")
                        .WithMany("Szerzodes")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("LorincMarton_WebAPI.Modells.Partner", b =>
                {
                    b.Navigation("Szerzodes");
                });
#pragma warning restore 612, 618
        }
    }
}
